site_name: Start Page
site_url: https://rainstormok.github.io/start-page
theme:
  name: material

nav:
  - Git: "Git.md"
  - HIT: "hit.md"
  - Config: "config.md"
	- Code style: "codeStyle.md"
	- c++: "cplusplus.md"
